<?php
/**
 * @autor: B.j.Ouwehand
 *
 */
/* Mason main page */

// the doctype helper
$doctypeHelper = new Zend_View_Helper_Doctype();
$doctypeHelper->doctype('HTML4_LOOSE');
echo $this->doctype();

?>
<html>
    <head>
        <?php echo $this->headLink()->appendStylesheet('/styles/styles.css'); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/jquery-1.10.2.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/masonry.pkgd.min.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/imagesloaded.js'), 'text/javascript'); ?>
<?
echo $this->headScript();
 ?>

    </head>
    <body>
        <div id="str-head"">
        </div>
        <div id="str-body">
            <div class="container">
            </div>
        </div>
        <script type="text/javascript" >
          /**
           * @autor: B.j.Ouwehand
           *
           * Proof of concept
           *
           */
            var container = document.querySelector('.container');
            var msnry;
            var url = '/mason/';
            $.ajax({
                url: url,
                dataType: 'json',
                type : 'get',
                success: function(data){
                    $.each(data, function( index, value ) {
                        console.log(value.name);

                        // create the html
                        var elem = $('<div/>', {
                            class: 'item',
                            text: value.name
                        })
                        elem.appendTo('.container');

                        // rewrite the masonry
                        var msnry = new Masonry(container);
                        msnry.appended( elem );
                        msnry.layout();

                    });
                }
            });
      </script>
    </body>
</html>