<?php
/**
 * @autor: B.j.Ouwehand
 *
 */
/* Mason main page */


?>

<html>
    <head>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/jquery-1.10.2.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/masonry.pkgd.min.js'), 'text/javascript'); ?>
        <?php echo $this->headScript()->prependFile($this->baseUrl('js/imagesloaded.js'), 'text/javascript'); ?>
        <style>
            #str-head {
                width:100%;
                height:300px;
                background-color: white;
                display: block;
                box-shadow: inset 0px -5px 5px #888888;
            }
            #str-body{
                clear:both;
                width: 100%;
                min-height: 500px;
            }
            .item { width: 200px; height:200px; background-color: #0099FF }
            .item.w2 { width: 500; height:500; background-color: #00CC00 }
        </style>

    </head>
    <body>
      <div id="str-head"">
        </div>
        <div id="str-body">
            <div id="container">
                <div class="item">...</div>
                <div class="item w2">...</div>
                <div class="item">...</div>
                <div class="item">...</div>
                <div class="item w2">...</div>
                <div class="item">...</div>
                <div class="item">...</div>
                <div class="item w2">...</div>
                <div class="item">...</div>
                <div class="item">...</div>
                <div class="item w2">...</div>
                <div class="item">...</div>
            </div>
        </div>
      <script type="text/javascript" >

          var container = document.querySelector('#container');
          var msnry;


          // initialize Masonry after all images have loaded
          imagesLoaded( container, function() {
              msnry = new Masonry( container);

              var elements = msnry.getItemElements();
              var elemNum = elements.length;
              console.log(elemNum);

              // hide all elements and fadein slow
              for ( var i = 0; i < elemNum; i++ ) {
                  elem = elements[i];
                  var item = msnry.getItem(elem);

                  //workaround
                  $(elem).hide();
              }

              // Mansonry jquery method not working
              // Workaround
              for ( var i = 0; i < elemNum; i++ ) {
                elem = elements[i];
                $(elem).fadeIn(i * 400);
              }

          });
      </script>
    </body>
</html>